"""empty message

Revision ID: 397bccd20b3a
Revises: fdc146e2d781
Create Date: 2023-09-15 16:59:54.703457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397bccd20b3a'
down_revision = 'fdc146e2d781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
